# -*- coding: utf-8 -*-
"""phase5_enhance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6SjljGiqqmzcf_ggFiuVm0qEPe5TNVk
"""

# phase5_enhance.py - Enhance model accuracy
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import joblib
import os
import glob
import sys

print("="*70)
print("🚀 HYBRID-FinInt: Phase 5 - Model Enhancement")
print("="*70)

# Load your data (AUTO-FIXED PATH)
data_patterns = [
    "data/colab/training_data_*.csv",
    "data/processed/with_sentiment_*.csv",
    "data/processed/with_indicators_*.csv"
]

data_path = None
for pattern in data_patterns:
    files = sorted(glob.glob(pattern))
    if files:
        data_path = files[-1]  # Latest file
        break

if data_path is None:
    print("❌ No training data found! Run phases 1-3 first.")
    sys.exit(1)

df = pd.read_csv(data_path, parse_dates=['Timestamp'])

print(f"📊 Data loaded: {len(df):,} records")

# ======================
# ENHANCEMENT 1: ADD LAGGED FEATURES
# ======================
print("\n1️⃣ ADDING LAGGED FEATURES...")

# Create lagged features (past 3 periods)
feature_cols = ['close', 'volume', 'RSI_14', 'MACD_Line', 'sentiment_score']
for col in feature_cols:
    if col in df.columns:
        for lag in [1, 2, 3]:
            df[f'{col}_lag{lag}'] = df.groupby('Symbol')[col].shift(lag)

# ======================
# ENHANCEMENT 2: ADD INTERACTION FEATURES
# ======================
print("2️⃣ ADDING INTERACTION FEATURES...")

if 'RSI_14' in df.columns and 'MACD_Line' in df.columns:
    df['RSI_MACD_interaction'] = df['RSI_14'] * df['MACD_Line']

if 'volume' in df.columns and 'Daily_Return' in df.columns:
    df['volume_return_interaction'] = df['volume'] * abs(df['Daily_Return'])

# ======================
# ENHANCEMENT 3: ADD ASSET-SPECIFIC FEATURES
# ======================
print("3️⃣ ADDING ASSET-SPECIFIC FEATURES...")

# Add asset type as feature
df['is_crypto'] = (df['Asset_Type'] == 'Crypto').astype(int)
df['is_stock'] = (df['Asset_Type'] == 'Stock').astype(int)

# ======================
# ENHANCEMENT 4: BETTER TARGET DEFINITION
# ======================
print("4️⃣ ENHANCING TARGET DEFINITION...")

# Instead of just next hour, predict if price increases by more than 0.5%
df['price_next'] = df.groupby('Symbol')['close'].shift(-1)
df['target_enhanced'] = ((df['price_next'] - df['close']) / df['close'] > 0.005).astype(int)

# Remove old target
if 'target' in df.columns:
    df = df.drop('target', axis=1)
df = df.rename(columns={'target_enhanced': 'target'})

# ======================
# ENHANCEMENT 5: ADD TIME-BASED FEATURES
# ======================
print("5️⃣ ADDING TIME-BASED FEATURES...")

df['hour'] = df['Timestamp'].dt.hour
df['day_of_week'] = df['Timestamp'].dt.dayofweek
df['is_market_hours'] = ((df['hour'] >= 9) & (df['hour'] <= 16)).astype(int)

# ======================
# PREPROCESS & TRAIN
# ======================
print("\n🔧 TRAINING ENHANCED MODEL...")

# Remove NaN from lagged features
df_clean = df.dropna()

print(f"📊 Clean records: {len(df_clean):,}")

# Select features
exclude_cols = ['Symbol', 'Timestamp', 'Asset_Type', 'price_next']
all_features = [col for col in df_clean.columns if col not in exclude_cols and col != 'target']
feature_cols = [col for col in all_features if df_clean[col].dtype in ['int64', 'float64']]

print(f"📈 Using {len(feature_cols)} enhanced features")

# Prepare data
X = df_clean[feature_cols].values
y = df_clean['target'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train enhanced model
enhanced_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

enhanced_model.fit(X_train_scaled, y_train)

# Predictions
y_pred = enhanced_model.predict(X_test_scaled)
accuracy = accuracy_score(y_test, y_pred)

print(f"\n✅ ENHANCED MODEL RESULTS:")
print(f"   Accuracy: {accuracy:.4f}")
print(f"   Improvement: +{(accuracy - 0.50):.4f}")

# Feature importance
feature_importance = pd.DataFrame({
    'feature': feature_cols,
    'importance': enhanced_model.feature_importances_
}).sort_values('importance', ascending=False)

print(f"\n🔝 TOP 15 ENHANCED FEATURES:")
print(feature_importance.head(15).to_string(index=False))

# Save enhanced model
os.makedirs('models', exist_ok=True)
joblib.dump(enhanced_model, 'models/enhanced_model.pkl')
joblib.dump(scaler, 'models/enhanced_scaler.pkl')

# ALSO save to root (where Sammar.py expects them)
joblib.dump(enhanced_model, 'random_forest_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
import pickle
with open('features.pkl', 'wb') as f:
    pickle.dump(feature_cols, f)
print("💾 Also saved to root directory for dashboard")

# Save feature list
with open('models/enhanced_features.pkl', 'wb') as f:
    pickle.dump(feature_cols, f)

print(f"\n💾 Enhanced model saved to 'models/' folder")

# ======================
# REAL SENTIMENT DATA
# ======================
print("\n" + "="*70)
print("📰 GETTING REAL SENTIMENT DATA")
print("="*70)

print("To improve accuracy above 55%, we need real sentiment data:")
print("\n🔑 GET FREE API KEYS:")
print("1. NewsAPI.org - 100 free requests/day")
print("2. Twitter API v2 - Free for academic use")
print("3. Reddit API - Free with registration")
print("\n📝 Add your API keys to sentiment/analyzer.py")

print("\n" + "="*70)
print("📈 EXPECTED IMPROVEMENTS WITH REAL DATA:")
print("="*70)
print("Current: ~50% accuracy (technical indicators only)")
print("With real sentiment: 55-60% accuracy")
print("With social media + news: 60-65% accuracy")
print("With macro data + alternative data: 65-70%+ accuracy")

print("\n🎯 NEXT STEPS:")
print("1. Get NewsAPI key (newsapi.org)")
print("2. Update sentiment analyzer with real API")
print("3. Collect 3-6 months of historical data")
print("4. Retrain models with real sentiment")