# -*- coding: utf-8 -*-
"""phase3_sentiment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fh3QRplcllYg9UdqyYOVgx6fsH6NCPiZ
"""

# phase3_sentiment.py - Sentiment Analysis Phase
import sys
import os
import pandas as pd
from datetime import datetime

# Add src to path
sys.path.append('src')

print("="*70)
print("😊 HYBRID-FinInt: Phase 3 - Sentiment Analysis")
print("="*70)

try:
    # Try to import from sentiment module
    try:
        from sentiment.analyzer import SentimentAnalyzer
        use_mock = False
    except ImportError:
        print("⚠ SentimentAnalyzer not found, using simple sentiment...")
        from sentiment.analyzer import SimpleSentiment
        use_mock = True

    # Load the latest processed data
    processed_folder = "data/processed"
    if not os.path.exists(processed_folder):
        print("❌ No processed data folder. Run phase 2 first!")
        sys.exit(1)

    # Find latest indicators file
    indicator_files = [f for f in os.listdir(processed_folder)
                      if f.startswith('with_indicators_') and f.endswith('.csv')]

    if not indicator_files:
        print("❌ No indicator files found. Run phase 2 first!")
        sys.exit(1)

    latest_file = sorted(indicator_files)[-1]
    data_path = os.path.join(processed_folder, latest_file)

    print(f"📁 Loading data from: {data_path}")
    df = pd.read_csv(data_path)
    print(f"✅ Loaded {len(df):,} records")

    # Get unique symbols
    symbols = df['Symbol'].unique().tolist()
    print(f"📈 Analyzing sentiment for {len(symbols)} symbols...")
    print(f"   Symbols: {', '.join(symbols[:5])}...")

    # Create sentiment folder if not exists
    os.makedirs('src/sentiment', exist_ok=True)

    # Analyze sentiment
    print("\n🔍 Analyzing market sentiment...")
    print("-" * 50)

    if use_mock:
        print("⚠ Using mock sentiment data (no API key configured)")
        sentiment_df = SimpleSentiment.generate_sentiment_scores(symbols)
    else:
        analyzer = SentimentAnalyzer()
        sentiment_df = analyzer.batch_sentiment_analysis(symbols)

    # Display results
    print("\n" + "="*50)
    print("📊 SENTIMENT ANALYSIS RESULTS")
    print("="*50)

    for _, row in sentiment_df.iterrows():
        symbol = row['symbol']
        score = row['sentiment_score']
        sentiment = row['sentiment']

        # Visual indicator
        if score > 0.3:
            indicator = "📈"
        elif score < -0.3:
            indicator = "📉"
        else:
            indicator = "📊"

        print(f"{indicator} {symbol:10} | Score: {score:6.3f} | Sentiment: {sentiment:10}")

    # Merge sentiment with price data
    print(f"\n🔄 Merging sentiment with price data...")

    # Add sentiment to each row based on symbol
    sentiment_dict = dict(zip(sentiment_df['symbol'], sentiment_df['sentiment_score']))
    df['sentiment_score'] = df['Symbol'].map(sentiment_dict)

    # Fill NaN sentiment scores with 0
    df['sentiment_score'] = df['sentiment_score'].fillna(0)

    # Add sentiment category
    df['sentiment'] = 'neutral'
    df.loc[df['sentiment_score'] > 0.2, 'sentiment'] = 'positive'
    df.loc[df['sentiment_score'] < -0.2, 'sentiment'] = 'negative'

    # Save combined data
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")
    output_file = f"data/processed/with_sentiment_{timestamp}.csv"

    df.to_csv(output_file, index=False)

    # Statistics
    sentiment_counts = df['sentiment'].value_counts()
    avg_sentiment = df['sentiment_score'].mean()

    print("\n" + "="*50)
    print("✅ SENTIMENT ANALYSIS COMPLETE!")
    print("="*50)
    print(f"📁 Saved to: {output_file}")
    print(f"📊 Records: {len(df):,}")
    print(f"😊 Average sentiment score: {avg_sentiment:.3f}")
    print(f"📈 Sentiment distribution:")
    for sentiment, count in sentiment_counts.items():
        percentage = (count / len(df)) * 100
        print(f"   • {sentiment:8}: {count:5} records ({percentage:.1f}%)")

    # Show correlation between sentiment and price change
    if 'Daily_Return' in df.columns:
        correlation = df['sentiment_score'].corr(df['Daily_Return'])
        print(f"📊 Sentiment-Price correlation: {correlation:.3f}")

except Exception as e:
    print(f"\n❌ ERROR: {e}")
    import traceback
    traceback.print_exc()

print("\n" + "="*70)
print("➡️ Next: Run 'phase4_train.py' for model training")
input("\nPress Enter to exit...")

