# -*- coding: utf-8 -*-
"""phase2_indicators

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6SjljGiqqmzcf_ggFiuVm0qEPe5TNVk
"""

# phase2_indicators.py - Save in main folder
import sys
import os
import pandas as pd
import numpy as np
from datetime import datetime

# Add src to path
sys.path.append('src')

print("="*70)
print("📊 HYBRID-FinInt: Phase 2 - Technical Indicators")
print("="*70)

try:
    from technical.indicators import TechnicalIndicators

    # Find latest data file
    raw_folder = "data/raw"
    if not os.path.exists(raw_folder):
        print("❌ No data folder found. Run phase 1 first!")
        sys.exit(1)

    # Get latest CSV file
    csv_files = [f for f in os.listdir(raw_folder) if f.endswith('.csv')]
    if not csv_files:
        print("❌ No CSV files found. Run phase 1 first!")
        sys.exit(1)

    latest_file = sorted(csv_files)[-1]
    data_path = os.path.join(raw_folder, latest_file)

    print(f"📁 Loading data from: {data_path}")
    df = pd.read_csv(data_path, parse_dates=['Timestamp'])
    print(f"✅ Loaded {len(df):,} records")
    print(f"📈 Assets: {df['Symbol'].unique()[:5]}...")

    # Create technical folder if not exists
    os.makedirs('src/technical', exist_ok=True)

    # Process each symbol
    print("\n🔧 Calculating technical indicators...")
    print("-" * 50)

    all_processed = []
    symbols = df['Symbol'].unique()

    for i, symbol in enumerate(symbols, 1):
        print(f"{i}/{len(symbols)} Processing {symbol}...")

        # Calculate indicators
        symbol_data = TechnicalIndicators.calculate_all_indicators(df, symbol)
        symbol_data = TechnicalIndicators.add_price_features(symbol_data)

        if len(symbol_data) > 0:
            all_processed.append(symbol_data)
            print(f"   ✓ Added {len(symbol_data)} records with indicators")
        else:
            print(f"   ⚠ Skipped {symbol} (insufficient data)")

    if all_processed:
        # Combine all processed data
        processed_df = pd.concat(all_processed, ignore_index=True)
        processed_df = processed_df.sort_values(['Timestamp', 'Symbol'])

        # Save processed data
        timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        output_file = f"data/processed/with_indicators_{timestamp}.csv"

        processed_df.to_csv(output_file, index=False)

        print("\n" + "="*50)
        print("✅ TECHNICAL INDICATORS COMPLETE!")
        print("="*50)
        print(f"📊 Processed {len(processed_df):,} records")
        print(f"📈 Assets: {len(processed_df['Symbol'].unique())}")
        print(f"📁 Saved to: {output_file}")

        # Show sample of indicators
        print("\n📋 SAMPLE INDICATORS (first row):")
        sample = processed_df.iloc[0]
        indicator_cols = [col for col in processed_df.columns if any(x in col for x in ['RSI', 'MACD', 'MA_', 'BB_', 'ATR'])]
        for col in indicator_cols[:10]:  # Show first 10
            if col in processed_df.columns:
                value = sample[col]
                if isinstance(value, (int, float, np.number)) and not pd.isna(value):
                    print(f"   {col}: {value:.4f}")
                else:
                    print(f"   {col}: {value}")

    else:
        print("❌ No data was processed!")

except ImportError as e:
    print(f"\n❌ IMPORT ERROR: {e}")
    print("\nMake sure indicators.py exists in src/technical/")

except Exception as e:
    print(f"\n❌ ERROR: {e}")
    import traceback
    traceback.print_exc()

print("\n" + "="*70)
print("➡️ Next: Run 'phase3_sentiment.py' for sentiment analysis")
input("\nPress Enter to exit...")