# -*- coding: utf-8 -*-
"""prepare_for_colab.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fh3QRplcllYg9UdqyYOVgx6fsH6NCPiZ
"""

# prepare_for_colab.py - Prepare data for Google Colab training
import pandas as pd
import os
from datetime import datetime
import numpy as np

print("="*70)
print("📤 PREPARING DATA FOR GOOGLE COLAB TRAINING")
print("="*70)

# Find latest sentiment data
processed_folder = "data/processed"
os.makedirs(processed_folder, exist_ok=True) # Ensure the directory exists
sentiment_files = [f for f in os.listdir(processed_folder)
                  if f.startswith('with_sentiment_') and f.endswith('.csv')]

if not sentiment_files:
    print("❌ No sentiment data found. Run phase 3 first!")
    exit(1)

latest_file = sorted(sentiment_files)[-1]
data_path = os.path.join(processed_folder, latest_file)

print(f"📁 Loading: {data_path}")
df = pd.read_csv(data_path, parse_dates=['Timestamp'])

print(f"✅ Loaded {len(df):,} records")
print(f"📈 Assets: {len(df['Symbol'].unique())}")

# Prepare data for ML
print("\n🔧 Preparing features for machine learning...")

# Select features for training
feature_columns = [
    'open', 'high', 'low', 'close', 'volume',
    'RSI_14', 'MACD_Line', 'MACD_Signal', 'MACD_Histogram',
    'BB_Upper_20', 'BB_Middle_20', 'BB_Lower_20', 'BB_Bandwidth_20',
    'MA_5', 'MA_10', 'MA_20', 'MA_50',
    'ATR_14', 'Daily_Return', 'Log_Return', 'HL_Spread',
    'sentiment_score'
]

# Create target: Next hour's price movement (1 if up, 0 if down)
df = df.sort_values(['Symbol', 'Timestamp'])
df['target'] = (df.groupby('Symbol')['close'].shift(-1) > df['close']).astype(int)

# Remove rows with NaN values (from indicators calculation)
df_clean = df.dropna(subset=feature_columns + ['target'])

print(f"\n📊 Data Statistics:")
print(f"   Total records: {len(df):,}")
print(f"   Clean records: {len(df_clean):,}")
print(f"   Features: {len(feature_columns)}")
print(f"   Target distribution:")
target_counts = df_clean['target'].value_counts()
for value, count in target_counts.items():
    direction = "UP" if value == 1 else "DOWN"
    percentage = (count / len(df_clean)) * 100
    print(f"     {direction}: {count:,} ({percentage:.1f}%) affinities")

# Save prepared data
timestamp = datetime.now().strftime("%Y%m%d_%H%M")
output_file = f"data/colab/training_data_{timestamp}.csv"
os.makedirs(os.path.dirname(output_file), exist_ok=True)

df_clean[['Symbol', 'Timestamp', 'Asset_Type'] + feature_columns + ['target']].to_csv(output_file, index=False)

print(f"\n💾 Saved prepared data: {output_file}")

# Also create a sample file for quick testing
sample_size = min(1000, len(df_clean))
sample_file = f"data/colab/training_sample_{timestamp}.csv"
df_clean.sample(sample_size, random_state=42).to_csv(sample_file, index=False)

print(f"📄 Sample data: {sample_file} ({sample_size} records)")

print("\n📋 NEXT STEPS FOR GOOGLE COLAB:")
print("1. Go to https://colab.research.google.com")
print("2. Create new notebook")
print("3. Upload the CSV file to Colab")
print("4. Use the training notebook template below")

print("\n" + "="*70)
print("📓 COLAB TRAINING NOTEBOOK TEMPLATE STARTS BELOW")
print("="*70)
print()
print('''# HYBRID-FinInt Model Training on Google Colab
# Import libraries
!pip install pandas numpy scikit-learn torch torchvision torchaudio xgboost

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

# Mount Google Drive (if your data is there)
from google.colab import drive
drive.mount('/content/drive')

# Load your data
# Option 1: Upload the CSV directly to Colab
# df = pd.read_csv('training_data_20260115_1506.csv')

# Option 2: Load from Google Drive
# df = pd.read_csv('/content/drive/MyDrive/Hybrid-FinInt/training_data.csv')

print("Data loaded!")
print(f"Shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")

# Continue with model training...
''')

