# -*- coding: utf-8 -*-
"""run

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6SjljGiqqmzcf_ggFiuVm0qEPe5TNVk
"""

import sys
import os

# Add src to Python path
sys.path.append('src')

print("="*70)
print("🚀 HYBRID-FinInt: AI-Powered Financial Intelligence System")
print("="*70)
print("Phase 1: Data Collection & Market Analysis")
print("-" * 70)

try:
    from data_collection.collector import HybridFinIntCollector

    # Create collector
    collector = HybridFinIntCollector()

    # Ask user
    print("\n📊 Available assets:")
    print(f"   Stocks: {len(collector.stocks)} assets")
    print(f"   Cryptocurrencies: {len(collector.cryptos)} assets")

    print("\n🔧 Options:")
    print("   1. Quick test (AAPL & BTC only)")
    print("   2. Full data collection (all assets)")
    print("   3. Exit")

    while True:
        choice = input("\nSelect option (1-3): ").strip()

        if choice == "1":
            print("\n" + "="*50)
            print("RUNNING QUICK TEST...")
            print("="*50)
            data = collector.quick_test()
            break

        elif choice == "2":
            print("\n" + "="*50)
            print("RUNNING FULL DATA COLLECTION...")
            print("="*50)
            data = collector.collect_all_data()
            break

        elif choice == "3":
            print("\n👋 Exiting...")
            sys.exit(0)

        else:
            print("❌ Invalid choice. Please enter 1, 2, or 3.")

    if data is not None:
        print("\n" + "="*70)
        print("✅ DATA COLLECTION COMPLETE!")
        print("="*70)

        # Show summary
        print(f"\n📊 COLLECTED DATA SUMMARY:")
        print(f"   • Total records: {len(data):,}")
        print(f"   • Assets: {len(data['Symbol'].unique())}")
        print(f"   • Time range: {data['Timestamp'].min()} to {data['Timestamp'].max()}")
        print(f"   • Data shape: {data.shape}")

        # Show assets
        print(f"\n📈 ASSETS COLLECTED:")
        for asset_type in data['Asset_Type'].unique():
            assets = data[data['Asset_Type'] == asset_type]['Symbol'].unique()
            print(f"   {asset_type}: {', '.join(assets[:5])}{'...' if len(assets) > 5 else ''}")

        print("\n📁 Check the 'data/' folder for CSV files")
        print("\n➡️ Next: Run 'python phase2_indicators.py' for technical analysis")

except ImportError as e:
    print(f"\n❌ IMPORT ERROR: {e}")
    print("\nMake sure:")
    print("1. collector.py exists in src/data_collection/")
    print("2. All packages are installed: pip install pandas yfinance")

except Exception as e:
    print(f"\n❌ ERROR: {e}")
    import traceback
    traceback.print_exc()

print("\n" + "="*70)
input("Press Enter to exit...")